### ISSUE TITLE
Make a new release to have a py3.12 compatible package

### ISSUE THREAD

**Issue by IAlibay** [MDAnalysis/MDAnalysisData#62] opened 2023-10-29 17:49 UTC
With #61 merged, we should try to make a new release.

I'm not sure what is the status of MDAnalysisData, we could stick on a deployment workflow or just make a bog standard release as-is.

**Comment by IAlibay** [comment] 2023-10-29 17:50
pinging @orbeckst here as the person in the know for this package

**Comment by orbeckst** [comment] 2023-10-29 20:11
Deployment workflow would be great (issue #57), not saying that this your job.

**Comment by orbeckst** [comment] 2023-10-30 19:20
With all the latest updates to CI, I feel ready for 0.9.0!

**Comment by orbeckst** [comment] 2023-10-30 19:32
Holding until PR #68 is merged.

**Comment by orbeckst** [comment] 2023-10-30 19:40
Created tag release-0.9.0...

**Comment by orbeckst** [comment] 2023-10-30 19:41
Failed: https://github.com/MDAnalysis/MDAnalysisData/actions/runs/6697894849 ...

**Comment by orbeckst** [comment] 2023-10-30 19:42
The workflow is not valid. .github/workflows/deploy.yaml (Line: 18, Col: 9): Unexpected end of expression: ')'. Located at position 120 within expression: github.repository == 'MDAnalysis/MDAnalysisData' &&
(github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')

... need to fix

**Comment by orbeckst** [comment] 2023-10-30 19:59
* ✅ TestPypi deployment itself worked https://github.com/MDAnalysis/MDAnalysisData/actions/runs/6698031942/job/18199197552
* 🔴 Test FAILED
  ```
  ==================================== ERRORS ====================================
  _________________ ERROR at setup of test_fetch_remote_sha_fail _________________
  file /home/runner/work/MDAnalysisData/MDAnalysisData/MDAnalysisData/tests/test_base.py, line   107
    def test_fetch_remote_sha_fail(remote_topology, mocker):
  E       fixture 'mocker' not found
  >       available fixtures: bunch, cache, capfd, capfdbinary, caplog, capsys, capsysbinary,   doctest_namespace, monkeypatch, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, remote_topology, some_text, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory
  >       use 'pytest --fixtures [testpath]' for help on them.
  ```

Need to add packages to the test suite.

**Comment by orbeckst** [comment] 2023-10-30 20:02
(When do I learn to use "rc" release tags when testing anything with deployment... sigh.)

**Comment by orbeckst** [comment] 2023-10-30 20:07
Progress currently blocked by #72 .

**Comment by orbeckst** [comment] 2023-10-30 20:10
(Note to self: test deployment with release-0.9.0-rc1, when all good, move the release-0.9.0 tag to HEAD and force-push tags, ignore resulting test.pypi failure, and hope that the upload to pypi works)

**Comment by orbeckst** [comment] 2023-10-31 14:45
WIth PR #73 merged we need to check that #72 is really fixed. 
- [ ] tag release-0.9.0-rc1
- [ ] check that the testpypi action uploads and completes the test

**Comment by IAlibay** [comment] 2023-10-31 14:47
0.9.0-rc1 won't work because pypi will always pick up a full release over an rc one and it's alreayd on testpypi.
You'll have to do 0.9.1-rc1 or alpha.

**Comment by orbeckst** [comment] 2023-10-31 14:53
You are right. However, in this particular case, the test was still a success: It uploaded 0.9.0-rc1 (which had already worked before), and it then successfully downloaded 0.9.0 '''and ran the tests''' — and it was really the latter that needed testing.

I'm fine with counting this as a success and moving on to releasing 0.9.0.

**Comment by orbeckst** [comment] 2023-10-31 15:08
Created the GitHub release https://github.com/MDAnalysis/MDAnalysisData/releases/tag/release-0.9.0

**Comment by orbeckst** [comment] 2023-10-31 16:16
Upload to https://pypi.org/project/MDAnalysisData/0.9.0/ was successful. (Testing in the action did not work as intended because it pulled 0.8.1.). Locally 0.9.0 works.

conda-forge is in progress with PR https://github.com/conda-forge/mdanalysisdata-feedstock/pull/8

**Comment by orbeckst** [comment] 2023-10-31 16:25
conda-forge is done.

**Closed by orbeckst** 2023-10-31 16:25 UTC
