### ISSUE TITLE
HTTPError: HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by Paulie-ai** [MDAnalysis/MDAnalysisData#59] opened 2023-02-18 13:49 UTC
when i try to 
adk_trans = datasets.fetch_adk_transitions_DIMS()

print(adk_trans.DESCR)
print(adk_trans.topology) 

it show 403 forbidden, how to fixed this error, thanks!

**Comment by orbeckst** [comment] 2023-09-18 17:29
I can't reproduce this error. 
```python
>>> import MDAnalysisData
>>> adk_trans = MDAnalysisData.datasets.fetch_adk_transitions_DIMS()
DIMS.tar.gz:  61%|███████████████████████████████▊                    | 448M/731M [00:57<00:41, 6.89MB/s]
>>> print(adk_trans.topology)
/Users/oliver/MDAnalysis_data/adk_transitions_DIMS/DIMS/topologies/adk4ake.psf 
```

Are you able to manually download the tar.gz files from https://doi.org/10.6084/m9.figshare.7165306.v2 or https://figshare.com/articles/dataset/Simulated_trajectory_ensembles_for_the_closed-to-open_transition_of_adenylate_kinase_from_DIMS_MD_and_FRODA/7165306/2 ?

**Comment by orbeckst** [comment] 2023-10-29 17:05
Without further feedback it's not clear what to do. Closing for now.

Please ask to re-open if the problem shows itself again.

**Closed by orbeckst** 2023-10-29 17:05 UTC
